import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="navbar">
            <div className="nav-left">
            <Link href='/' className="logo">READIPING</Link>
            </div>
            <div className="nav-center">
              <Link href="/reading">독서포럼</Link>     
              <Link href="/bookclub">북클럼</Link>
              <Link href="/market">장터</Link>  
              <Link href="/review">서평</Link>         
            </div>
            <div className="nav-right">
              <span style={{marginRight:'10px'}}>
                로그인
              </span>
            </div>
        </div>
        {children}
      </body>
    </html>
  );
}
